// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Videoteca.BLL;

#nullable disable

namespace Videoteca.Migrations
{
    [DbContext(typeof(VideotecaContext))]
    partial class VideotecaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Videoteca.BLL.AtorBLL", b =>
                {
                    b.Property<string>("NOME_ATOR")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("APOSENTADO")
                        .HasColumnType("bit");

                    b.Property<int>("IDADE")
                        .HasColumnType("int");

                    b.Property<string>("PAIS")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("NOME_ATOR");

                    b.ToTable("AtorBLL");
                });

            modelBuilder.Entity("Videoteca.BLL.ElencoFilmeBLL", b =>
                {
                    b.Property<int>("ID_ELENCO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_ELENCO"), 1L, 1);

                    b.Property<int>("ID_FILME")
                        .HasColumnType("int");

                    b.Property<string>("NOME_ATOR")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_ELENCO");

                    b.HasIndex("ID_FILME");

                    b.HasIndex("NOME_ATOR");

                    b.ToTable("ElencoFilmeBLL");
                });

            modelBuilder.Entity("Videoteca.BLL.ElencoSerieBLL", b =>
                {
                    b.Property<int>("ID_ELENCO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_ELENCO"), 1L, 1);

                    b.Property<int>("ID_SERIE")
                        .HasColumnType("int");

                    b.Property<string>("NOME_ATOR")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_ELENCO");

                    b.HasIndex("ID_SERIE");

                    b.HasIndex("NOME_ATOR");

                    b.ToTable("ElencoSerieBLL");
                });

            modelBuilder.Entity("Videoteca.BLL.FilmeBLL", b =>
                {
                    b.Property<int>("ID_FILME")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_FILME"), 1L, 1);

                    b.Property<int>("ANO")
                        .HasColumnType("int");

                    b.Property<bool>("ASSISTIDO")
                        .HasColumnType("bit");

                    b.Property<int>("AVALIACAO")
                        .HasColumnType("int");

                    b.Property<string>("DESCRICAO")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("DURACAO")
                        .HasColumnType("int");

                    b.Property<string>("GENERO")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("PAIS")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("TITULO_FILME")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_FILME");

                    b.ToTable("FilmeBLL");
                });

            modelBuilder.Entity("Videoteca.BLL.SerieBLL", b =>
                {
                    b.Property<int>("ID_SERIE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_SERIE"), 1L, 1);

                    b.Property<int>("ANO")
                        .HasColumnType("int");

                    b.Property<bool>("ASSISTIDO")
                        .HasColumnType("bit");

                    b.Property<int>("AVALIACAO")
                        .HasColumnType("int");

                    b.Property<string>("CAPITULO")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DESCRICAO")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("DURACAO")
                        .HasColumnType("int");

                    b.Property<int>("EPISODIO")
                        .HasColumnType("int");

                    b.Property<string>("GENERO")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PAIS")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TEMPORADA")
                        .HasColumnType("int");

                    b.Property<string>("TITULO_SERIE")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_SERIE");

                    b.ToTable("SerieBLL");
                });

            modelBuilder.Entity("Videoteca.BLL.ElencoFilmeBLL", b =>
                {
                    b.HasOne("Videoteca.BLL.FilmeBLL", "Filme")
                        .WithMany()
                        .HasForeignKey("ID_FILME")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Videoteca.BLL.AtorBLL", "Ator")
                        .WithMany()
                        .HasForeignKey("NOME_ATOR")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ator");

                    b.Navigation("Filme");
                });

            modelBuilder.Entity("Videoteca.BLL.ElencoSerieBLL", b =>
                {
                    b.HasOne("Videoteca.BLL.SerieBLL", "Serie")
                        .WithMany()
                        .HasForeignKey("ID_SERIE")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Videoteca.BLL.AtorBLL", "Ator")
                        .WithMany()
                        .HasForeignKey("NOME_ATOR")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ator");

                    b.Navigation("Serie");
                });
#pragma warning restore 612, 618
        }
    }
}
